name: sample_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Your local plugins
  morfinauth_usb:
    path: ../plugins/morfinauth_usb
  morfinauth_ble:
    path: ../plugins/morfinauth_ble

  # Standard packages
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.1

  # Packages required by your UI logic
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  lottie: ^3.1.0
  asn1lib: ^1.5.0
  pointycastle: ^3.7.3
  path_provider: ^2.1.2

  shared_preferences: ^2.2.2
  gson: ^0.1.6-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Registered Assets
  assets:
    - assets/images/
    - assets/animations/